#!/usr/bin/env php
<?php
$zweiComposerAutoload = __DIR__.'/autoload.php';
if (!file_exists($zweiComposerAutoload)) {
    $zweiComposerAutoload = dirname(dirname(__DIR__)).'/autoload.php';
}
include_once $zweiComposerAutoload;

$queueKey = $argv[1];
$service = new \Zwei\RabbitMqEvent\Queue\Service\StandardService();
$service->work($queueKey);