#!/usr/bin/env php
<?php
// 计划任务
$zweiComposerAutoload = __DIR__.'/vendor/autoload.php';
if (!file_exists($zweiComposerAutoload)) {
    $zweiComposerAutoload = dirname(dirname(__DIR__)).'/autoload.php';
}
include_once $zweiComposerAutoload;

$cronName   = $argv[1];
$obj        = new Zwei\RabbitMqEvent\Cron\Cron();
$obj->run($cronName);