#!/usr/bin/env php
<?php
$zweiComposerAutoload = __DIR__.'/vendor/autoload.php';
if (!file_exists($zweiComposerAutoload)) {
    $zweiComposerAutoload = dirname(dirname(__DIR__)).'/autoload.php';
}
include_once $zweiComposerAutoload;

$queueKey = "rabbit_queue_gateway";
$service = new \Zwei\RabbitMqEvent\Queue\Service\GatewayService();
$service->work($queueKey);