event_user_register: # 用户注册
  queue_key: "rabbit_queue_single" # 队列名
  broadcast: true # 是否广播
  callback: "\\Demo\\Product.buy" # 回调
event_send_sms: # 发送短信
  queue_name: multi_queue # 队列名
  broadcast: false # 是否广播
  callback: "\\Demo\\Send.message" # 回调